name: Haskell CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cabal-build:
    name: Cabal - os-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ghc:
          - 8.8.4

    env:
      CONFIG: "--enable-tests --enable-benchmarks"

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Setup Haskell Build Environment
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Cabal Update
        run: cabal update $CONFIG

      - name: Cabal Freeze
        run: cabal freeze $CONFIG

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: cabal-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build
        run: cabal build $CONFIG

      - name: Test
        run: cabal test $CONFIG