name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Set up Cachix
        uses: cachix/cachix-action@v10
        with:
          name: rkaippully
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Packages
        run: nix build --print-build-logs --no-link
