name: Haskell CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  stack-build:
    name: Stack - os-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ghc:
          - 8.8.4

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Setup Haskell Build Environment
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: 8.8.4
          enable-stack: true

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}

      - name: Clean Cache
        if: ${{ runner.os == 'macOS' }}
        run: |
          # Workaround for random errors on macos
          rm -rf ~/.stack/setup-exe-src ~/.stack/setup-exe-cache

      - name: Build
        run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: stack test --system-ghc --ta '--quickcheck-tests 100000'

      - name: Prepare sdist
        run: stack sdist --system-ghc
